image:
    - Visual Studio 2022
    - Ubuntu

version: "{branch}.{build}"
for:
    -
      matrix:
        only:
          - image: Ubuntu
      clone_folder: ~/imewlconverter
      build_script:
        - dotnet build ./src/ImeWlConverterCmd --configuration Release
      after_build:
        - cd ./src/ImeWlConverterCmd/bin/Release/net6.0
        - tar czvf ./imewlconverter_Linux_Mac.tar.gz *
        - mv ./imewlconverter_Linux_Mac.tar.gz ~/imewlconverter
        - cd ~/imewlconverter
    #   - dotnet ./ImeWlConverterCmd.dll -?
      test_script:
        - cd ./src/ImeWlConverterCoreTest
        - dotnet add ImeWlConverterCoreTest.csproj package Appveyor.TestLogger --version 2.0.0
        - cd ../..
        - dotnet test --test-adapter-path:. --logger:Appveyor ./src/ImeWlConverterCoreTest/ImeWlConverterCoreTest.csproj --configuration Release
      artifacts:
        - path: imewlconverter_Linux_Mac.tar.gz
          name: DotnetCore
      deploy:
        tag: $(APPVEYOR_REPO_TAG_NAME)
        release: imewlconverter-$(APPVEYOR_REPO_TAG_NAME)
        description: 'New Release'
        provider: GitHub
        auth_token:
            secure: XLH30sjOKisCZ2+ehPEf+7NVmaKdH8khPqwfT8BOOg6X6TWo48ptjgj21SZPHrYl            # your encrypted token from GitHub
        artifact: imewlconverter_Linux_Mac.tar.gz            # upload all NuGet packages to release assets
        draft: false
        prerelease: false
        force_update: true
        on:
            branch: master                 # release from master branch only
            APPVEYOR_REPO_TAG: true        # deploy on tag push only
    -
      matrix:
        only:
          - image: Visual Studio 2019
      clone_folder: C:\imewlconverter
      before_build:
        - SET SLNPATH=%APPVEYOR_BUILD_FOLDER%\src\IME WL Converter WinForm.sln
        - SET DIST=%APPVEYOR_BUILD_FOLDER%\src\IME WL Converter Win\bin\Release\net6.0-windows
      
        - MSBuild "%SLNPATH%" -t:restore
        - nuget restore "%SLNPATH%"
      build_script:
        - MSBuild "%SLNPATH%" /t:Rebuild /p:Configuration=Release
        - 7z a imewlconverter_Windows.zip "%DIST%\*.exe" "%DIST%\*.dll" "%DIST%\Readme.txt" "%DIST%\*.runtimeconfig.json"
      after_build:
      test_script:
        - nunit3-console "C:\imewlconverter\src\ImeWlConverterCoreTest\bin\Release\net6.0\ImeWlConverterCoreTest.dll" -result=myresults.xml;format=AppVeyor
      artifacts:
        - path: imewlconverter_Windows.zip
          name: WinForm
      deploy:
        tag: $(appveyor_repo_tag_name)
        release: imewlconverter-$(appveyor_repo_tag_name)
        description: 'New Release'
        provider: GitHub
        auth_token:
            secure: XLH30sjOKisCZ2+ehPEf+7NVmaKdH8khPqwfT8BOOg6X6TWo48ptjgj21SZPHrYl            # your encrypted token from GitHub
        artifact: imewlconverter_Windows.zip            # upload all NuGet packages to release assets
        draft: false
        prerelease: false
        force_update: true
        on:
            branch: master                 # release from master branch only
            APPVEYOR_REPO_TAG: true        # deploy on tag push only

 


